/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @DisplayName("get random quotes")
    @Test void quotesTest() {
        String path = "./src/test/resources/recentquotes.json";
        List allTheQuotes = App.getQuotes(path);
        ArrayList<String> quoteList = new ArrayList<>();
        for (Object j : allTheQuotes) {
            quoteList.add(j.toString());
        }

       assertEquals(true, quoteList.contains("{author='George Orwell', likes='183 likes', text=' “Man serves the interests of no creature except himself.�? '}"));
      //  assertEquals(true,quoteList.contains("{author='George Orwell', likes='183 likes', text=' “Man serves the interests of no creature except himself.�? '}"));
    }
}
